#include "stdio.h"
#include "string.h"
int main()
{
    char str[1000][20];
    int n,i,answer[10][500],count[10],number=0,j,zeronum,bigonenum,role[10],time,ok,identity,
    others,nott,divine,evil,human,lying,day,night;
    while(scanf("%d",&n)==1)
    {
        if(n==0) break;
        getchar();
        memset(str,0,sizeof(str));
        for(i=1;i<=n;i++)
            gets(str[i]);
        printf("Conversation #%d\n",++number);
        memset(count,0,sizeof(count));
        for(role[1]=1;role[1]<=3;role[1]++)
        for(role[2]=1;role[2]<=3;role[2]++)
        for(role[3]=1;role[3]<=3;role[3]++)
        for(role[4]=1;role[4]<=3;role[4]++)
        for(role[5]=1;role[5]<=3;role[5]++)
        for(time=1;time<=2;time++)
        {
            ok=1;
            for(i=1;i<=n;i++)
            {
                identity=str[i][0]-64;
                nott=0;
                for(j=0;str[i][j+3]!='\0';j++)
                    if(str[i][j]=='n'&&str[i][j+1]=='o'&&str[i][j+2]=='t')
                    {nott=1;break;}
                divine=0;
                for(j=0;str[i][j+2]!='\0';j++)
                    if(str[i][j]=='d'&&str[i][j+1]=='i')
                    {divine=1;break;}
                evil=0;
                for(j=0;str[i][j+2]!='\0';j++)
                    if(str[i][j]=='e'&&str[i][j+1]=='v')
                    {evil=1;break;}
                human=0;
                for(j=0;str[i][j+2]!='\0';j++)
                    if(str[i][j]=='h'&&str[i][j+1]=='u')
                    {human=1;break;}
                lying=0;
                for(j=0;str[i][j+2]!='\0';j++)
                    if(str[i][j]=='l'&&str[i][j+1]=='y')
                    {lying=1;break;}
                day=0;
                for(j=0;str[i][j+2]!='\0';j++)
                    if(str[i][j]=='d'&&str[i][j+1]=='a')
                    {day=1;break;}
                night=0;
                for(j=0;str[i][j+2]!='\0';j++)
                    if(str[i][j]=='n'&&str[i][j+1]=='i')
                    {night=1;break;}
                if(str[i][3]=='I')
                    others=identity;
                else others=str[i][3]-64;
                if(role[identity]==1)
                {
                    if(day==1)
                    {
                        if(nott==1)
                        {
                            if(time==1)
                            {ok=0;break;}
                        }
                        else
                        {
                            if(time==2)
                            {ok=0;break;}
                        }
                    }
                    if(night==1)
                    {
                        if(nott==1)
                        {
                            if(time==2)
                            {ok=0;break;}
                        }
                        else
                        {
                            if(time==1)
                            {ok=0;break;}
                        }
                    }
                    if(divine==1)
                    {
                        if(nott==1)
                        {
                            if(role[others]==1)
                            {ok=0;break;}
                        }
                        else
                        {
                            if(role[others]!=1)
                            {ok=0;break;}
                        }
                    }
                    if(evil==1)
                    {
                        if(nott==1)
                        {
                            if(role[others]==2)
                            {ok=0;break;}
                        }
                        else
                        {
                            if(role[others]!=2)
                            {ok=0;break;}
                        }
                    }
                    if(human==1)
                    {
                        if(nott==1)
                        {
                            if(role[others]==3)
                            {ok=0;break;}
                        }
                        else
                        {
                            if(role[others]!=3)
                            {ok=0;break;}
                        }
                    }
                    if(lying==1)
                    {
                        if(nott==1)
                        {
                            if(role[others]==2)
                            {ok=0;break;}
                            else if(time==2&&role[others]==3)
                            {ok=0;break;}
                        }
                        else
                        {
                            if(role[others]==1)
                            {ok=0;break;}
                            else if(role[others]==3&&time==1)
                            {ok=0;break;}
                        }
                    }
                }
                else if(role[identity]==2)
                {
                    if(day==1)
                    {
                        if(nott==1)
                        {
                            if(time!=1)
                            {ok=0;break;}
                        }
                        else
                        {
                            if(time==1)
                            {ok=0;break;}
                        }
                    }
                    if(night==1)
                    {
                        if(nott==1)
                        {
                            if(time!=2)
                            {ok=0;break;}
                        }
                        else
                        {
                            if(time==2)
                            {ok=0;break;}
                        }
                    }
                    if(divine==1)
                    {
                        if(nott==1)
                        {
                            if(role[others]!=1)
                            {ok=0;break;}
                        }
                        else
                        {
                            if(role[others]==1)
                            {ok=0;break;}
                        }
                    }
                    if(evil==1)
                    {
                        if(nott==1)
                        {
                            if(role[others]!=2)
                            {ok=0;break;}
                        }
                        else
                        {
                            if(role[others]==2)
                            {ok=0;break;}
                        }
                    }
                    if(human==1)
                    {
                        if(nott==1)
                        {
                            if(role[others]!=3)
                            {ok=0;break;}
                        }
                        else
                        {
                            if(role[others]==3)
                            {ok=0;break;}
                        }
                    }
                    if(lying==1)
                    {
                        if(nott==1)
                        {
                            if(role[others]==1)
                            {ok=0;break;}
                            else if(time==1&&role[others]==3)
                            {ok=0;break;}
                        }
                        else
                        {
                            if(role[others]==2)
                            {ok=0;break;}
                            else if(role[others]==3&&time==2)
                            {ok=0;break;}
                        }
                    }
                }
                else if(role[identity]==3)
                {
                    if(day==1)
                    {
                        if(nott==1)
                        {
                            ok=0;break;
                        }
                    }
                    if(night==1)
                    {
                        if(nott==0)
                        {
                            ok=0;break;
                        }
                    }
                    if(divine==1)
                    {
                        if(nott==1)
                        {
                            if(time==1&&role[others]==1)
                            {ok=0;break;}
                            else if(time==2&&role[others]!=1)
                            {ok=0;break;}
                        }
                        else
                        {
                            if(time==1&&role[others]!=1)
                            {ok=0;break;}
                            else if(time==2&&role[others]==1)
                            {ok=0;break;}
                        }
                    }
                    if(evil==1)
                    {
                        if(nott==1)
                        {
                            if(time==1&&role[others]==2)
                            {ok=0;break;}
                            else if(time==2&&role[others]!=2)
                            {ok=0;break;}
                        }
                        else
                        {
                            if(time==1&&role[others]!=2)
                            {ok=0;break;}
                            else if(time==2&&role[others]==2)
                            {ok=0;break;}
                        }
                    }
                    if(human==1)
                    {
                        if(nott==1)
                        {
                            if(time==1&&role[others]==3)
                            {ok=0;break;}
                            else if(time==2&&role[others]!=3)
                            {ok=0;break;}
                        }
                        else
                        {
                            if(time==1&&role[others]!=3)
                            {ok=0;break;}
                            else if(time==2&&role[others]==3)
                            {ok=0;break;}
                        }
                    }
                    if(lying==1)
                    {
                        if(nott==1)
                        {
                            if(time==1&&role[others]==2)
                            {ok=0;break;}
                            else if(time==2&&role[others]==1)
                            {ok=0;break;}
                        }
                        else
                        {
                            if(time==1&&role[others]==1)
                            {ok=0;break;}
                            else if(time==1&&role[others]==3)
                            {ok=0;break;}
                            else if(role[others]==3&&time==2)
                            {ok=0;break;}
                            else if(role[others]==2&&time==2)
                            {ok=0;break;}
                        }
                    }
                }
                }
                if(ok==1)
                {
                    for(j=1;j<=5;j++)
                    {
                        if(role[j]==answer[j][count[j]])
                            continue;
                        ++count[j];
                        answer[j][count[j]]=role[j];
                    }
                    if(answer[6][count[6]]!=time)
                    {
                        ++count[6];
                        answer[6][count[6]]=time;
                    }
                }
                }
                zeronum=0;
                bigonenum=0;
                for(i=1;i<=6;i++)
                {
                    if(count[i]==0)
                        ++zeronum;
                    else if(count[i]>1)
                        ++bigonenum;
                }
                if(zeronum>0)
                    printf("This is impossible.\n\n");
                else if(bigonenum==6)
                    printf("No facts are deducible.\n\n");
                else
                {
                    for(i=1;i<=5;i++)
                    if(count[i]==1)
                    {
                        printf("%c is ",i+64);
                        if(answer[i][1]==1)
                            printf("divine.\n");
                        else if(answer[i][1]==2)
                            printf("evil.\n");
                        else printf("human.\n");
                    }
                    if(count[6]==1)
                        if(answer[6][1]==1)
                            printf("It is day.\n");
                        else printf("It is night.\n");
                    printf("\n");
                }
    } 
                return 0;
}